server:
  port: 8080

spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NAVER_EMAIL}
    password: ${NAVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  info:
    key: ${API_KEY}
  time:
    key: ${API_TIME_KEY}
  master:
    key: ${API_MASTER_KEY}

naver:
  api:
    client:
      id: ${NAVER_API_CLIENT_ID}
      secret: ${NAVER_API_CLIENT_SECRET}

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ap-northeast-2  # 서울
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}