spring:
  datasource:
    url: jdbc:mysql://${DB_DEV_IP}/dev_db?useSSL=false&serverTimezone=UTC
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver   # 8 버전

  jpa:
    hibernate:
      ddl-auto: create-drop  # 데이터베이스 자동 생성/업데이트. 필요에 따라 'none'이나 'create'로 설정 가능.
    show-sql: true      # SQL 쿼리를 콘솔에 출력할지 여부
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  #OAuth - naver login
  #registration
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: mema
            client-id: ${NAVER_CILENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://${SERVER_IP}:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - nickname
              - email
        #provider
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

custom:
  code: ${PASSWORD_ENCODE}